### ISSUE TITLE
Decide on project name

### ISSUE THREAD

**Issue by recidive** [choko-org/choko-redux#9]
Decide on naming, maybe we should refactor a little and rename this redux-boot, redux-bricks?

**Comment by sebas5384** [comment]
- redux-boot
- redux-assembly
- redux-kernel
- redux-bricks
- redux-system
- redux-genesis
- redux-foundation
- redux-factory
- redux-hub
- redux-seed

**Comment by sebas5384** [comment]
And the winner is ... **redux-boot**
